"""
Django settings for videoapp project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Load .env file ──────────────────────────────────────────────
# Works for both `manage.py runserver` and `manage.py process_async_task`
def _load_dotenv(base: Path):
    for candidate in [base / '.env', base.parent / '.env', base.parent.parent / '.env']:
        if candidate.is_file():
            with open(candidate) as _f:
                for _line in _f:
                    _line = _line.strip()
                    if not _line or _line.startswith('#') or '=' not in _line:
                        continue
                    _k, _v = _line.split('=', 1)
                    _k = _k.strip()
                    _v = _v.strip().strip("'").strip('"')
                    if ' #' in _v:
                        _v = _v.split(' #')[0].strip().strip("'").strip('"')
                    if _k not in os.environ:
                        os.environ[_k] = _v
            break

_load_dotenv(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-0037%n_gby*ph4b7o(iaw)g!wbk5+-=b_y&p+d^dhhb7a0lvo_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() not in ('false', '0', 'no')

_allowed = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
     'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'videoapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'videoapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_path = os.environ.get('DB_PATH', '')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(_db_path) if _db_path else BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Media files (for uploads)
import os
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
_media_root = os.environ.get('MEDIA_ROOT', '')
MEDIA_ROOT = _media_root if _media_root else os.path.join(BASE_DIR, 'media')

# Allow frontend origin (if React runs on http://localhost:8080)
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

CORS_ALLOW_ALL_ORIGINS = True

# Unified logging — both web server and task worker write to the same log directory
import os as _os
LOG_DIR = _os.environ.get('LOG_DIR', '') or _os.path.join(BASE_DIR, 'logs')
_os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] [{asctime}] [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 20 * 1024 * 1024,  # 20 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'task_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _os.path.join(LOG_DIR, 'task_processor.log'),
            'maxBytes': 20 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _os.path.join(LOG_DIR, 'errors.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'LectureMind': {
            'handlers': ['console', 'app_file', 'task_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# ── Media sub-directories ────────────────────────────────────────────────────
# Resolved as absolute paths under MEDIA_ROOT unless an absolute path is given.
def _media_subdir(env_var: str, default: str) -> str:
    val = _os.environ.get(env_var, default)
    if _os.path.isabs(val):
        return val
    return _os.path.join(MEDIA_ROOT, val)

MEDIA_AUDIO_DIR      = _media_subdir('MEDIA_AUDIO_DIR',      'audio')
MEDIA_STREAMS_DIR    = _media_subdir('MEDIA_STREAMS_DIR',    'streams')
MEDIA_THUMBNAILS_DIR = _media_subdir('MEDIA_THUMBNAILS_DIR', 'thumbnails')

# ChromaDB persistent directory
CHROMA_PERSIST_DIR = _os.environ.get('CHROMA_PERSIST_DIR', '') or _os.path.join(MEDIA_ROOT, 'chromadb')

# Backend port used by `manage.py runserver` via the run_server management helper
BACKEND_PORT = int(_os.environ.get('BACKEND_PORT', 8000))